### ISSUE TITLE
invalid byte sequence

### ISSUE THREAD

**Issue by fatum** [fatum/api-extractor#10]
[11847:INFO] 2012-07-31 22:34:12 :: Status: 500, Content-Length: 71, Response Time: 596.84ms
Detect encoding from header: utf-8
[11847:ERROR] 2012-07-31 22:34:12 :: invalid byte sequence in UTF-8
[11847:ERROR] 2012-07-31 22:34:12 :: /srv/projects/extractor/releases/20120731183059/lib/extractor/readability.rb:47:in `scan'
/srv/projects/extractor/releases/20120731183059/lib/extractor/readability.rb:47:in`meta_charset'
/srv/projects/extractor/releases/20120731183059/lib/extractor/readability.rb:21:in `detect_encoding'
/srv/projects/extractor/releases/20120731183059/lib/extractor/readability.rb:11:in`get_content'
/srv/projects/extractor/releases/20120731183059/lib/extractor/readability.rb:5:in `analyze'
/srv/projects/extractor/releases/20120731183059/lib/extract_manager.rb:33:in`block in extract_data_from'
/srv/projects/extractor/releases/20120731183059/lib/extract_manager.rb:32:in `each'
/srv/projects/extractor/releases/20120731183059/lib/extract_manager.rb:32:in`extract_data_from'
/srv/projects/extractor/releases/20120731183059/lib/extract_manager.rb:17:in `perform'
extractor.rb:23:in`response'

**Comment by fatum** [comment]
Потенциальное решение - http://blog.grayproductions.net/articles/ruby_19s_string
